import React from 'react';
import { createFromIconfontCN } from '@ant-design/icons';

const IconFont = createFromIconfontCN({
    scriptUrl: '//at.alicdn.com/t/font_8d5l8fzk5b87iudi.js',
});

export const IconList = () => {
    return (
        <div style={{fontSize:20, display:"flex", flexWrap:"wrap",padding:50}}>
                <IconFont type="icon-facebook"/>icon-facebook<br/>
                <IconFont type="icon-tuichu"/>icon-tuichu<br/>
                <IconFont type="icon-twitter"/>icon-twitter<br/>
                <IconFont type="icon-fanhui"/>icon-fanhui<br/>
                <IconFont type="icon-xiangyou"/>icon-xiangyou<br/>
                <IconFont type="icon-right"/>icon-right<br/>
                <IconFont type="icon-fanhui1"/>icon-fanhui1<br/>
                <IconFont type="icon-fenxiang"/>icon-fenxiang<br/>
                <IconFont type="icon-xiangxia"/>icon-xiangxia<br/>
                <IconFont type="icon-xiangxia1"/>icon-xiangxia1<br/>
                <IconFont type="icon-xiangxia2"/>icon-xiangxia2<br/>
                <IconFont type="icon-suofang"/>icon-suofang<br/>
                <IconFont type="icon-esc"/>icon-esc<br/>
                <IconFont type="icon-chexiao"/>icon-chexiao<br/>
                <IconFont type="icon-chexiao1"/>icon-chexiao1<br/>
                <IconFont type="icon-suoding"/>icon-suoding<br/>
                <IconFont type="icon-bianji"/>icon-bianji<br/>
                <IconFont type="icon-shoucang2"/>icon-shoucang2<br/>
                <IconFont type="icon-shoucang1"/>icon-shoucang1<br/>
                <IconFont type="icon-xinjian"/>icon-xinjian<br/>
                <IconFont type="icon-gongkai"/>icon-gongkai<br/>
                <IconFont type="icon-gouwuche1"/>icon-gouwuche1<br/>
                <IconFont type="icon-gouwuche2"/>icon-gouwuche2<br/>
                <IconFont type="icon-zhongwen"/>icon-zhongwen<br/>
                <IconFont type="icon-shangchuan"/>icon-shangchuan<br/>
                <IconFont type="icon-yingwen"/>icon-yingwen<br/>
                <IconFont type="icon-shanchu"/>icon-shanchu<br/>
                <IconFont type="icon-xiazai"/>icon-xiazai<br/>
                <IconFont type="icon-sousuo"/>icon-sousuo<br/>
                <IconFont type="icon-dashang"/>icon-dashang<br/>
                <IconFont type="icon-xiangmu"/>icon-xiangmu<br/>
                <IconFont type="icon-fuzhidaima1"/>icon-fuzhidaima1<br/>
                <IconFont type="icon-wofaqi"/>icon-wofaqi<br/>
                <IconFont type="icon-xiangmuchengyuan"/>icon-xiangmuchengyuan<br/>
                <IconFont type="icon-gengduo"/>icon-gengduo<br/>
                <IconFont type="icon-wocanyu"/>icon-wocanyu<br/>
            <IconFont type="icon-lishi" />icon-lishi<br/>
            <IconFont type="icon-piliang" />icon-piliang<br/>
            <IconFont type="icon-shijian" />icon-shijian<br/>
            <IconFont type="icon-gonggao" />icon-gonggao<br/>
            <IconFont type="icon-weixin" />icon-weixin<br/>
            <IconFont type="icon-weibo" />icon-weibo<br/>
            <IconFont type="icon-gerenzhanghu" />icon-gerenzhanghu<br/>
            <IconFont type="icon-tianjiachengyuan" />icon-tianjiachengyuan<br/>
            <IconFont type="icon-soutubiao" />icon-soutubiao<br/>
            <IconFont type="icon-souren" />icon-souren<br/>
            <IconFont type="icon-yuzhanghao" />icon-yuzhanghao<br/>
            <IconFont type="icon-biaoqing" />icon-biaoqing<br/>
            <IconFont type="icon-qq" />icon-qq<br/>
            <IconFont type="icon-weibo1" />icon-weibo1<br/>
            <IconFont type="icon-zuoxuan" />icon-zuoxuan<br/>
            <IconFont type="icon-fangda2" />icon-fangda2<br/>
            <IconFont type="icon-zuo2" />icon-zuo2<br/>
            <IconFont type="icon-suoxiao" />icon-suoxiao<br/>
            <IconFont type="icon-you2" />icon-you2<br/>
            <IconFont type="icon-suoxiao2" />icon-suoxiao2<br/>
            <IconFont type="icon-youxuan2" />icon-youxuan2<br/>
            <IconFont type="icon-zuo" />icon-zuo<br/>
            <IconFont type="icon-zuoxuan2" />icon-zuoxuan2<br/>
            <IconFont type="icon-shang" />icon-shang<br/>
            <IconFont type="icon-shang2" />icon-shang2<br/>
            <IconFont type="icon-youxuan" />icon-youxuan<br/>
            <IconFont type="icon-xia" />icon-xia<br/>
            <IconFont type="icon-fangda" />icon-fangda<br/>
            <IconFont type="icon-you" />icon-you<br/>
            <IconFont type="icon-zhuanrang" />icon-zhuanrang<br/>
            <IconFont type="icon-dianzan" />icon-dianzan<br/>
            <IconFont type="icon-huifu" />icon-huifu<br/>
            <IconFont type="icon-saoyisao" />icon-saoyisao<br/>
            <IconFont type="icon-shuoming" />icon-shuoming<br/>
            <IconFont type="icon-jinggao" />icon-jinggao<br/>
            <IconFont type="icon-jieshi" />icon-jieshi<br/>
            <IconFont type="icon-youxiang" />icon-youxiang<br/>
            <IconFont type="icon-guanbi" />icon-guanbi<br/>
            <IconFont type="icon-qunzhu" />icon-qunzhu<br/>
            <IconFont type="icon-fuzhichenggong" />icon-fuzhichenggong<br/>
            <IconFont type="icon-weijiaru" />icon-weijiaru<br/>
            <IconFont type="icon-daishenhe" />icon-daishenhe<br/>
            <IconFont type="icon-shenhetongguo" />icon-shenhetongguo<br/>
            <IconFont type="icon-shenhejujue" />icon-shenhejujue<br/>
            <IconFont type="icon-xinjiantubiaoku" />icon-xinjiantubiaoku<br/>
            <IconFont type="icon-tubiaoku" />icon-tubiaoku<br/>
            <IconFont type="icon-gouwuche" />icon-gouwuche<br/>
            <IconFont type="icon-huidingbu" />icon-huidingbu<br/>
            <IconFont type="icon-dianzan1" />icon-dianzan1<br/>
            <IconFont type="icon-morentouxiang" />icon-morentouxiang<br/>
            <IconFont type="icon-paixu" />icon-paixu<br/>
            <IconFont type="icon-wenjian" />icon-wenjian<br/>
            <IconFont type="icon-github" />icon-github<br/>
            <IconFont type="icon-yuzhanghao1" />icon-yuzhanghao1<br/>
            <IconFont type="icon-weibo2" />icon-weibo2<br/>
            <IconFont type="icon-you1" />icon-you1<br/>
            <IconFont type="icon-zuo1" />icon-zuo1<br/>
            <IconFont type="icon-shang1" />icon-shang1<br/>
            <IconFont type="icon-iconfont1" />icon-iconfont1<br/>
            <IconFont type="icon-gonggaodayi" />icon-gonggaodayi<br/>
            <IconFont type="icon-gongnengjieshao" />icon-gongnengjieshao<br/>
            <IconFont type="icon-tubiaohuizhi" />icon-tubiaohuizhi<br/>
            <IconFont type="icon-daimayingyong" />icon-daimayingyong<br/>
            <IconFont type="icon-zhifubao" />icon-zhifubao<br/>
            <IconFont type="icon-alibaba" />icon-alibaba<br/>
            <IconFont type="icon-xiaomi" />icon-xiaomi<br/>
            <IconFont type="icon-zhongguodianxin" />icon-zhongguodianxin<br/>
            <IconFont type="icon-tianmao" />icon-tianmao<br/>
            <IconFont type="icon-alimama" />icon-alimama<br/>
            <IconFont type="icon-zhubajie" />icon-zhubajie<br/>
            <IconFont type="icon-tengxunwang" />icon-tengxunwang<br/>
            <IconFont type="icon-aliyun" />icon-aliyun<br/>
            <IconFont type="icon-taobaowang" />icon-taobaowang<br/>
            <IconFont type="icon-anzhuo" />icon-anzhuo<br/>
            <IconFont type="icon-ios" />icon-ios<br/>
            <IconFont type="icon-pcduan" />icon-pcduan<br/>
            <IconFont type="icon-qingchu" />icon-qingchu<br/>
            <IconFont type="icon-huizhiguize" />icon-huizhiguize<br/>
            <IconFont type="icon-zhizuoliucheng" />icon-zhizuoliucheng<br/>
            <IconFont type="icon-fuzhidaima" />icon-fuzhidaima<br/>
            <IconFont type="icon-fankui1" />icon-fankui1<br/>
            <IconFont type="icon-weitijiao" />icon-weitijiao<br/>
            <IconFont type="icon-chexiao2" />icon-chexiao2<br/>
        </div>
    )
}
